/**
 * @license Copyright 2026 Otto SPDX-License-Identifier: Apache-2.0
 */

import { cleanup, fireEvent, render, screen, waitFor } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { App } from './App.js';
import type {
  EnterpriseAccount,
  EnterpriseOrganizationFeatures,
} from '../preload/index.js';
import { openParkServices } from './components/ParkServicesPlugin.js';

const harness = vi.hoisted(() => ({
  auth: { current: null as unknown },
  centralIdentity: {
    current: { edition: 'personal' as 'personal' | 'enterprise', role: 'member', profiles: [] },
  },
  storeActions: {
    cancel: vi.fn(),
    clearError: vi.fn(),
    createSession: vi.fn(),
    deleteSession: vi.fn(),
    launchAgentProfile: vi.fn(),
    launchAgentProfileWithPrompt: vi.fn(),
    cancelPendingAgentLaunches: vi.fn(),
    postSystemNote: vi.fn(),
    renameSession: vi.fn(),
    respondToolConfirmation: vi.fn(),
    selectSession: vi.fn(),
    sendMessage: vi.fn(),
    setModel: vi.fn(),
  },
  settingsActions: {
    clearExportMessage: vi.fn(),
    exportConversation: vi.fn(),
  },
  updateActions: { silentCheck: vi.fn() },
  moduleCapabilityRetry: vi.fn(),
  organizationFeatures: {
    current: {
      enterprise_tree: true,
      park_service: true,
      feishu_auto_reply: true,
      direct_messages: true,
      atoa: true,
      knowledge: true,
      skill_market: true,
    },
  },
  configuredOrganizationFeatures: {
    current: {
      enterprise_tree: true,
      park_service: true,
      feishu_auto_reply: true,
      direct_messages: true,
      atoa: true,
      knowledge: true,
      skill_market: true,
    },
  },
  productActions: {
    addFriend: vi.fn(),
    clearError: vi.fn(),
    confirmPendingAutoSkill: vi.fn(),
    createSchedule: vi.fn(),
    deleteSchedule: vi.fn(),
    refreshPendingAutoSkills: vi.fn(),
    rejectPendingAutoSkill: vi.fn(),
    selectDate: vi.fn(),
  },
  frameHandlers: new Set<(frame: unknown) => void>(),
  send: vi.fn(),
}));

vi.mock('./state/useEnterpriseAuth.js', () => ({
  useEnterpriseAuth: () => harness.auth.current,
}));

vi.mock('./state/useOttoStore.js', () => ({
  useOttoStore: () => ({
    state: {
      connection: 'connected',
      sessions: {
        session_1: {
          sessionId: 'session_1',
          title: 'Test',
          status: 'idle',
          messageCount: 1,
          updatedAt: '2026-08-11T00:00:00.000Z',
        },
      },
      sessionIds: ['session_1'],
      activeSessionId: 'session_1',
      messages: { session_1: [] },
      models: [{ id: 'test-model', name: 'Test model' }],
      modelsLoaded: true,
      sessionsLoaded: true,
      currentModel: 'test-model',
      slashCommands: [],
      lastError: null,
      queuedCounts: {},
      pendingCreateRequestId: null,
      unreadSessions: [],
    },
    actions: harness.storeActions,
  }),
  selectSortedSessions: () => [],
}));

vi.mock('./state/useSettingsData.js', () => ({
  useSettingsData: () => ({
    state: { exportMessage: null },
    actions: harness.settingsActions,
  }),
}));

vi.mock('./state/useSoftwareUpdate.js', () => ({
  useSoftwareUpdate: () => ({
    state: { badgeVisible: false },
    actions: harness.updateActions,
  }),
}));

vi.mock('./state/useProductWorkspace.js', () => ({
  useProductWorkspace: () => ({
    state: {
      workspace: null,
      schedules: [],
      pendingAutoSkills: [],
      lastAutoSkillAction: null,
      selectedDate: '2026-08-11',
      error: null,
    },
    actions: harness.productActions,
  }),
}));

vi.mock('./state/useModuleWorkspaceCapabilities.js', () => ({
  useModuleWorkspaceCapabilities: () => ({
    status: 'ready',
    ready: true,
    modules: [],
    organizationFeatures: harness.organizationFeatures.current,
    organizationFeatureState: {
      configured: harness.configuredOrganizationFeatures.current,
      entitled: harness.organizationFeatures.current,
      effective: harness.organizationFeatures.current,
    },
    baselineEnterpriseTreeAvailable:
      harness.configuredOrganizationFeatures.current.enterprise_tree,
    baselineDirectMessagesAvailable:
      harness.configuredOrganizationFeatures.current.direct_messages,
    parkIdentity: null,
    retry: harness.moduleCapabilityRetry,
  }),
}));

vi.mock('./state/centralEnterpriseIdentity.js', () => ({
  resolveCentralEnterpriseIdentity: () => harness.centralIdentity.current,
}));

vi.mock('./agents/departmentAgents.js', () => ({
  setAutoGeneratedAgentProfiles: vi.fn(),
}));

vi.mock('./components/EnterpriseLoginPage.js', () => ({
  EnterpriseLoginPage: () => <div data-testid="login-page" />,
}));

vi.mock('./components/Sidebar.js', () => ({
  Sidebar: ({
    onOpenHub,
    onOpenAccounts,
  }: {
    onOpenHub: () => void;
    onOpenAccounts?: () => void;
  }) => (
    <>
      <button type="button" onClick={onOpenHub}>open-preferences</button>
      {onOpenAccounts ? (
        <button type="button" onClick={onOpenAccounts}>open-accounts</button>
      ) : null}
    </>
  ),
}));

vi.mock('./components/AccountManagementPage.js', () => ({
  AccountManagementPage: ({
    onOrganizationChanged,
  }: {
    onOrganizationChanged?: () => void;
  }) => (
    <button type="button" onClick={onOrganizationChanged}>simulate-organization-change</button>
  ),
}));

vi.mock('./components/ChatView.js', () => ({
  ChatView: ({
    rightPanelCollapsed,
    onToggleRightPanel,
    pendingAgent,
    onOpenSetup,
    onRespondQuestion,
  }: {
    rightPanelCollapsed?: boolean;
    onToggleRightPanel?: () => void;
    pendingAgent?: { title: string } | null;
    onOpenSetup?: () => void;
    onRespondQuestion?: (
      callId: string,
      outcome: 'approved',
      payload?: unknown,
      tool?: unknown,
    ) => void;
  }) => (
    <main data-testid="chat-view">
      {pendingAgent ? <span data-testid="pending-agent">{pendingAgent.title}</span> : null}
      {onToggleRightPanel ? (
        <button
          type="button"
          aria-label={rightPanelCollapsed ? '展开右侧栏' : '折叠右侧栏'}
          onClick={onToggleRightPanel}
        >
          toggle-right-panel
        </button>
      ) : null}
      {onOpenSetup ? (
        <button type="button" onClick={onOpenSetup}>open-model-settings</button>
      ) : null}
      {onRespondQuestion ? (
        <>
          <button type="button" onClick={() => onRespondQuestion(
            'enterprise-list-members',
            'approved',
            undefined,
            {
              confirmationDetails: { rootCommand: 'enterprise_collaboration' },
              parameters: { action: 'list_members' },
            },
          )}>simulate-enterprise-list-members</button>
          <button type="button" onClick={() => onRespondQuestion(
            'enterprise-assign-member',
            'approved',
            undefined,
            {
              confirmationDetails: { rootCommand: 'enterprise_collaboration' },
              parameters: {
                action: 'assign_member_position',
                recipientAccountId: 'peer-1',
                department: '研发部',
                positionTitle: '工程师',
              },
            },
          )}>simulate-enterprise-assign-member</button>
          <button type="button" onClick={() => onRespondQuestion(
            'enterprise-send-message',
            'approved',
            undefined,
            {
              confirmationDetails: { rootCommand: 'enterprise_collaboration' },
              parameters: {
                action: 'send_message',
                recipientAccountId: 'peer-1',
                content: 'hello',
              },
            },
          )}>simulate-enterprise-send-message</button>
          <button type="button" onClick={() => onRespondQuestion(
            'enterprise-ask-peer-otto',
            'approved',
            undefined,
            {
              confirmationDetails: { rootCommand: 'enterprise_collaboration' },
              parameters: {
                action: 'ask_peer_otto',
                recipientAccountId: 'peer-1',
                question: 'status?',
              },
            },
          )}>simulate-enterprise-ask-peer-otto</button>
          <button type="button" onClick={() => onRespondQuestion(
            'enterprise-consult-peer-otto',
            'approved',
            undefined,
            {
              confirmationDetails: { rootCommand: 'enterprise_collaboration' },
              parameters: {
                action: 'consult_peer_otto',
                recipientAccountId: 'peer-1',
                question: 'plan?',
              },
            },
          )}>simulate-enterprise-consult-peer-otto</button>
        </>
      ) : null}
    </main>
  ),
}));

vi.mock('./setup/SetupPanel.js', () => ({
  SetupPanel: ({
    models,
    saving,
    onSave,
  }: {
    models: unknown[];
    saving: boolean;
    onSave: (payload: {
      provider: string;
      baseUrl: string;
      apiKey: string;
      modelId: string;
      enabled: boolean;
      makeActive: boolean;
    }) => void;
  }) => (
    <section data-testid="setup-panel" data-model-count={models.length} data-saving={saving}>
      <button
        type="button"
        onClick={() => onSave({
          provider: 'openai',
          baseUrl: 'https://api.deepseek.com/v1',
          apiKey: 'test-key-never-rendered',
          modelId: 'deepseek-chat',
          enabled: true,
          makeActive: true,
        })}
      >
        save-deepseek
      </button>
    </section>
  ),
}));

vi.mock('./components/RightPanel.js', () => ({
  RightPanel: ({
    collapsed,
    onActivate,
  }: {
    collapsed?: boolean;
    onActivate?: (module: {
      id: string;
      label: string;
      category: 'common';
      icon: 'agent';
      availability: 'available';
      activation:
        | { kind: 'agent'; profileId: string }
        | { kind: 'dialog'; dialog: 'park'; target: 'announcement' }
        | { kind: 'dialog'; dialog: 'enterprise-memory' }
        | { kind: 'route'; route: 'skillzone' };
    }) => void;
  }) => (
    <aside data-testid="work-panel" data-collapsed={collapsed ? 'true' : 'false'}>
      <button type="button" onClick={() => onActivate?.({
        id: 'park-announcement', label: '园区公告', category: 'common', icon: 'agent',
        availability: 'available', activation: { kind: 'dialog', dialog: 'park', target: 'announcement' },
      })}>activate-park</button>
      <button type="button" onClick={() => onActivate?.({
        id: 'enterprise-memory', label: '企业记忆', category: 'common', icon: 'agent',
        availability: 'available', activation: { kind: 'dialog', dialog: 'enterprise-memory' },
      })}>activate-memory</button>
      <button type="button" onClick={() => onActivate?.({
        id: 'skill-zone', label: 'Skill 专区', category: 'common', icon: 'agent',
        availability: 'available', activation: { kind: 'route', route: 'skillzone' },
      })}>activate-skill-zone</button>
      <button type="button" onClick={() => onActivate?.({
        id: 'agent-ppt', label: 'PPT 创作专家', category: 'common', icon: 'agent',
        availability: 'available', activation: { kind: 'agent', profileId: 'ppt' },
      })}>activate-agent</button>
    </aside>
  ),
}));

vi.mock('./components/WorkspaceDialogs.js', () => ({
  EnterpriseMemoryDialog: ({ open }: { open: boolean }) => (
    open ? <div data-testid="enterprise-memory-dialog" /> : null
  ),
  AutoSkillDialog: () => null,
  CustomAgentManagerDialog: () => null,
}));

vi.mock('./components/SkillZonePage.js', () => ({
  SkillZonePage: () => <main data-testid="skill-zone-page" />,
}));

vi.mock('./components/ParkServicesPlugin.js', () => ({
  ParkServicesPlugin: () => null,
  PARK_STATE_EVENT: 'otto:park-services-state',
  openParkServices: vi.fn(),
  closeParkServices: vi.fn(),
  hideParkServices: vi.fn(),
}));

vi.mock('./components/SettingsHubPage.js', () => ({
  SettingsHubPage: () => <section data-testid="settings-hub">settings-content</section>,
}));

vi.mock('./components/WhatsNewDialog.js', () => ({
  WhatsNewDialog: () => <div data-testid="whats-new" />,
}));

vi.mock('./components/ProactiveToast.js', () => ({
  ProactiveToast: () => null,
}));

const accountA: EnterpriseAccount = {
  id: 'account-a',
  organizationId: 'personal-a',
  organizationName: 'Personal',
  accountType: 'personal',
  employeeId: null,
  username: 'account-a',
  phone: null,
  name: 'Alice',
  role: null,
  department: null,
  positionId: null,
  positionTitle: null,
  isAdmin: false,
  status: 'active',
  tags: [],
  createdAt: '2026-08-11T00:00:00.000Z',
  updatedAt: '2026-08-11T00:00:00.000Z',
};

function authFor(account: EnterpriseAccount | null, status: 'loading' | 'signed-out' | 'signed-in') {
  return {
    state: {
      status,
      account,
      serverUrl: 'https://enterprise.example.com/',
      registrationIntent: null,
      busy: false,
      error: null,
    },
    actions: {
      loginWithPassword: vi.fn(),
      requestLoginCode: vi.fn(),
      loginWithSms: vi.fn(),
      requestRegistrationCode: vi.fn(),
      register: vi.fn(),
      clearError: vi.fn(),
      joinEnterprise: vi.fn(),
      logout: vi.fn(),
    },
  };
}

function configureEnterpriseWorkspace(
  featurePatch: Partial<EnterpriseOrganizationFeatures> = {},
): void {
  harness.auth.current = authFor({
    ...accountA,
    accountType: 'enterprise',
    organizationId: 'organization-a',
    organizationName: '测试企业',
  }, 'signed-in');
  harness.centralIdentity.current = {
    edition: 'enterprise',
    role: 'member',
    profiles: [],
  };
  Object.assign(harness.organizationFeatures.current, featurePatch);
  Object.assign(harness.configuredOrganizationFeatures.current, featurePatch);
}

function rightPanelPreferenceKey(account: EnterpriseAccount): string {
  return [
    'otto.right-panel.v1',
    'https://enterprise.example.com',
    account.organizationId,
    account.id,
  ].map(encodeURIComponent).join(':');
}

beforeEach(() => {
  localStorage.clear();
  harness.auth.current = authFor(accountA, 'signed-in');
  harness.centralIdentity.current = { edition: 'personal', role: 'member', profiles: [] };
  Object.assign(harness.organizationFeatures.current, {
    enterprise_tree: true,
    park_service: true,
    feishu_auto_reply: true,
    direct_messages: true,
    atoa: true,
    knowledge: true,
    skill_market: true,
  });
  Object.assign(harness.configuredOrganizationFeatures.current, {
    enterprise_tree: true,
    park_service: true,
    feishu_auto_reply: true,
    direct_messages: true,
    atoa: true,
    knowledge: true,
    skill_market: true,
  });
  Object.defineProperty(window, 'otto', {
    configurable: true,
    writable: true,
    value: {
      ...window.otto,
      autoGeneratedAgentProfiles: vi.fn(() => new Promise(() => undefined)),
      // These tests do not exercise customer-module discovery. Keep the
      // unrelated background request pending so it cannot update App after a
      // synchronous assertion has already completed.
      customerModuleInstalledList: vi.fn(() => new Promise(() => undefined)),
      enterpriseMessagesUnread: vi.fn(() => new Promise(() => undefined)),
      generateCustomAgent: vi.fn(),
      onMenu: vi.fn(() => vi.fn()),
      onNotificationSessionOpen: vi.fn(() => vi.fn()),
      send: harness.send,
      onFrame: vi.fn((handler: (frame: unknown) => void) => {
        harness.frameHandlers.add(handler);
        return () => harness.frameHandlers.delete(handler);
      }),
    } as unknown as Window['otto'],
  });
});

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
  harness.frameHandlers.clear();
});

describe('App workspace UI integration', () => {
  it('shows boot and login states without entering the workspace', () => {
    harness.auth.current = authFor(null, 'loading');
    const view = render(<App />);
    expect(screen.getByRole('status')).toBeTruthy();

    harness.auth.current = authFor(null, 'signed-out');
    view.rerender(<App />);
    expect(screen.getByTestId('login-page')).toBeTruthy();
  });

  it('always starts in the unified workspace UI without a legacy mode selector', () => {
    render(<App />);

    expect(document.querySelector('.otto-app')).toBeTruthy();
    expect(screen.getByTestId('work-panel')).toBeTruthy();
    expect(screen.getByTestId('whats-new')).toBeTruthy();
    expect(screen.getByRole('button', { name: '折叠右侧栏' })).toBeTruthy();
  });

  it('keeps the workspace panel mounted while settings are open', () => {
    render(<App />);

    expect(screen.getByTestId('work-panel')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: 'open-preferences' }));
    expect(screen.getByTestId('settings-hub')).toBeTruthy();
    expect(screen.getByTestId('work-panel').dataset.collapsed).toBe('false');
    expect(screen.getByTestId('work-panel')).toBeTruthy();
  });

  it('toggles the right panel from the chat header and persists the account preference', () => {
    const first = render(<App />);

    expect(screen.getByTestId('work-panel').dataset.collapsed).toBe('false');
    fireEvent.click(screen.getByRole('button', { name: '折叠右侧栏' }));

    expect(screen.getByTestId('work-panel').dataset.collapsed).toBe('true');
    expect(screen.getByRole('button', { name: '展开右侧栏' })).toBeTruthy();
    expect(localStorage.getItem(rightPanelPreferenceKey(accountA))).toBe('collapsed');

    first.unmount();
    render(<App />);
    expect(screen.getByTestId('work-panel').dataset.collapsed).toBe('true');
    expect(screen.getByRole('button', { name: '展开右侧栏' })).toBeTruthy();
  });

  it('keeps a collapsed right panel mounted while the settings hub is open', () => {
    localStorage.setItem(rightPanelPreferenceKey(accountA), 'collapsed');
    render(<App />);

    expect(screen.getByTestId('work-panel').dataset.collapsed).toBe('true');
    fireEvent.click(screen.getByRole('button', { name: 'open-preferences' }));

    expect(screen.getByTestId('settings-hub')).toBeTruthy();
    expect(screen.getByTestId('work-panel').dataset.collapsed).toBe('true');
  });

  it('routes workspace modules through the existing App-level activation chains', () => {
    harness.centralIdentity.current = { edition: 'enterprise', role: 'member', profiles: [] };
    render(<App />);

    fireEvent.click(screen.getByRole('button', { name: 'activate-park' }));
    expect(openParkServices).toHaveBeenCalledWith('announcement');

    fireEvent.click(screen.getByRole('button', { name: 'activate-memory' }));
    expect(screen.getByTestId('enterprise-memory-dialog')).toBeTruthy();

    fireEvent.click(screen.getByRole('button', { name: 'activate-agent' }));
    expect(screen.getByTestId('pending-agent').textContent).toBe('PPT 创作专家');

    fireEvent.click(screen.getByRole('button', { name: 'activate-skill-zone' }));
    expect(screen.getByTestId('skill-zone-page')).toBeTruthy();
  });

  it('uses the next account right-panel preference on the account-switch render', () => {
    const accountB = {
      ...accountA,
      id: 'account-b',
      organizationId: 'personal-b',
      username: 'account-b',
      name: 'Bob',
    };
    localStorage.setItem(rightPanelPreferenceKey(accountA), 'collapsed');
    const view = render(<App />);
    expect(screen.getByTestId('work-panel').dataset.collapsed).toBe('true');

    harness.auth.current = authFor(accountB, 'signed-in');
    view.rerender(<App />);

    expect(screen.getByTestId('work-panel').dataset.collapsed).toBe('false');
    expect(screen.getByRole('button', { name: '折叠右侧栏' })).toBeTruthy();
  });

  it('keeps the unified workspace UI when the account changes', () => {
    const view = render(<App />);
    expect(screen.getByTestId('work-panel')).toBeTruthy();

    const accountB = {
      ...accountA,
      id: 'account-b',
      organizationId: 'personal-b',
      username: 'account-b',
      name: 'Bob',
    };
    harness.auth.current = authFor(accountB, 'signed-in');
    view.rerender(<App />);

    expect(screen.getByTestId('work-panel')).toBeTruthy();
  });

  it('refreshes the model list whenever personal API settings are opened', async () => {
    render(<App />);

    fireEvent.click(screen.getByRole('button', { name: 'open-model-settings' }));

    expect(screen.getByTestId('setup-panel')).toBeTruthy();
    await waitFor(() => {
      expect(harness.send).toHaveBeenCalledWith({ type: 'get_models', payload: {} });
    });
  });

  it('does not miss an immediate matching models_list response after saving DeepSeek', async () => {
    harness.send.mockImplementation((frame: { type?: string }) => {
      if (frame.type !== 'save_custom_model') return;
      for (const handler of harness.frameHandlers) {
        handler({
          type: 'models_list',
          payload: {
            models: [
              {
                id: 'custom:openai:deepseek-chat@abc123',
                displayName: 'DeepSeek deepseek-chat',
                provider: 'openai',
                baseUrl: 'https://api.deepseek.com/v1',
                modelId: 'deepseek-chat',
                enabled: true,
              },
            ],
          },
        });
      }
    });
    render(<App />);
    fireEvent.click(screen.getByRole('button', { name: 'open-model-settings' }));

    fireEvent.click(screen.getByRole('button', { name: 'save-deepseek' }));

    await waitFor(() => expect(screen.getByTestId('chat-view')).toBeTruthy());
    expect(screen.queryByTestId('setup-panel')).toBeNull();
  });

  it('refreshes global effective capabilities after enterprise organization settings change', () => {
    const adminAccount: EnterpriseAccount = {
      ...accountA,
      accountType: 'enterprise',
      organizationId: 'organization-a',
      organizationName: '测试企业',
      isAdmin: true,
    };
    harness.auth.current = authFor(adminAccount, 'signed-in');
    harness.centralIdentity.current = {
      edition: 'enterprise',
      role: 'company_admin',
      profiles: [],
    };

    render(<App />);
    fireEvent.click(screen.getByRole('button', { name: 'open-accounts' }));
    fireEvent.click(screen.getByRole('button', { name: 'simulate-organization-change' }));

    expect(harness.moduleCapabilityRetry).toHaveBeenCalledOnce();
  });

  it('does not execute enterprise message tool actions when direct_messages is not effective', () => {
    configureEnterpriseWorkspace({ direct_messages: false });
    const enterpriseMessageSend = vi.fn();
    Object.assign(window.otto, { enterpriseMessageSend });

    render(<App />);
    fireEvent.click(screen.getByRole('button', { name: 'simulate-enterprise-send-message' }));

    expect(enterpriseMessageSend).not.toHaveBeenCalled();
    expect(harness.storeActions.respondToolConfirmation).toHaveBeenCalledWith(
      'enterprise-send-message',
      'approved',
      {
        newContent: JSON.stringify({
          ok: false,
          error: '企业私聊未启用或当前服务器未授权',
        }),
      },
    );
  });

  it('polls same-organization baseline messaging without probing unentitled Federation', async () => {
    configureEnterpriseWorkspace({ direct_messages: false });
    harness.configuredOrganizationFeatures.current.direct_messages = true;
    const enterpriseMessagesUnread = vi.fn(async () => []);
    const enterprisePresenceHeartbeat = vi.fn(async () => undefined);
    const enterpriseFederationContacts = vi.fn(async () => {
      throw new Error('commercial module is not entitled');
    });
    Object.assign(window.otto, {
      enterpriseMessagesUnread,
      enterprisePresenceHeartbeat,
      enterpriseFederationContacts,
    });

    render(<App />);

    await waitFor(() => expect(enterpriseMessagesUnread).toHaveBeenCalled());
    await waitFor(() => expect(enterprisePresenceHeartbeat).toHaveBeenCalled());
    expect(enterpriseFederationContacts).not.toHaveBeenCalled();
  });

  it('does not execute organization tool actions when enterprise_tree is not effective', () => {
    configureEnterpriseWorkspace({ enterprise_tree: false });
    const enterpriseOrganizationView = vi.fn();
    const enterpriseAccountUpdate = vi.fn();
    Object.assign(window.otto, { enterpriseOrganizationView, enterpriseAccountUpdate });

    render(<App />);
    fireEvent.click(screen.getByRole('button', { name: 'simulate-enterprise-list-members' }));
    fireEvent.click(screen.getByRole('button', { name: 'simulate-enterprise-assign-member' }));

    expect(enterpriseOrganizationView).not.toHaveBeenCalled();
    expect(enterpriseAccountUpdate).not.toHaveBeenCalled();
    expect(harness.storeActions.respondToolConfirmation).toHaveBeenCalledWith(
      'enterprise-list-members',
      'approved',
      {
        newContent: JSON.stringify({
          ok: false,
          error: '企业组织目录未启用',
        }),
      },
    );
    expect(harness.storeActions.respondToolConfirmation).toHaveBeenCalledWith(
      'enterprise-assign-member',
      'approved',
      {
        newContent: JSON.stringify({
          ok: false,
          error: '企业组织树未启用或当前服务器未授权',
        }),
      },
    );
  });

  it('keeps baseline member listing while advanced tree assignment is not entitled', async () => {
    configureEnterpriseWorkspace({ enterprise_tree: false });
    harness.configuredOrganizationFeatures.current.enterprise_tree = true;
    const enterpriseOrganizationView = vi.fn(async () => ({
      organization: {
        id: 'organization-a', name: '测试企业', status: 'active' as const,
        createdAt: '2026-08-11T00:00:00.000Z',
      },
      members: [],
      employeeCount: 0,
    }));
    const enterpriseAccountUpdate = vi.fn();
    Object.assign(window.otto, { enterpriseOrganizationView, enterpriseAccountUpdate });

    render(<App />);
    fireEvent.click(screen.getByRole('button', { name: 'simulate-enterprise-list-members' }));
    fireEvent.click(screen.getByRole('button', { name: 'simulate-enterprise-assign-member' }));

    await waitFor(() => expect(enterpriseOrganizationView).toHaveBeenCalledOnce());
    expect(enterpriseAccountUpdate).not.toHaveBeenCalled();
    expect(harness.storeActions.respondToolConfirmation).toHaveBeenCalledWith(
      'enterprise-assign-member',
      'approved',
      {
        newContent: JSON.stringify({
          ok: false,
          error: '企业组织树未启用或当前服务器未授权',
        }),
      },
    );
  });

  it('does not execute Otto ask or consult tool actions when atoa is not effective', () => {
    configureEnterpriseWorkspace({ direct_messages: true, atoa: false });
    const enterpriseMessageSend = vi.fn();
    Object.assign(window.otto, { enterpriseMessageSend });

    render(<App />);
    fireEvent.click(screen.getByRole('button', { name: 'simulate-enterprise-ask-peer-otto' }));
    fireEvent.click(screen.getByRole('button', { name: 'simulate-enterprise-consult-peer-otto' }));

    expect(enterpriseMessageSend).not.toHaveBeenCalled();
    expect(harness.storeActions.respondToolConfirmation).toHaveBeenCalledWith(
      'enterprise-ask-peer-otto',
      'approved',
      {
        newContent: JSON.stringify({
          ok: false,
          error: 'Otto 协作未启用或当前服务器未授权',
        }),
      },
    );
    expect(harness.storeActions.respondToolConfirmation).toHaveBeenCalledWith(
      'enterprise-consult-peer-otto',
      'approved',
      {
        newContent: JSON.stringify({
          ok: false,
          error: 'Otto 协作未启用或当前服务器未授权',
        }),
      },
    );
  });

  it('closes a pending tool consultation when atoa effective access is revoked', async () => {
    configureEnterpriseWorkspace({ enterprise_tree: true, direct_messages: true, atoa: true });
    const peer = {
      id: 'peer-1',
      username: 'peer-1',
      name: '同事一',
      role: '成员',
      department: '研发部',
      positionId: null,
      positionTitle: '工程师',
      isAdmin: false,
      status: 'active' as const,
    };
    Object.assign(window.otto, {
      enterpriseOrganizationView: vi.fn(async () => ({
        organization: {
          id: 'organization-a',
          name: '测试企业',
          status: 'active' as const,
          createdAt: '2026-08-11T00:00:00.000Z',
        },
        members: [peer],
        employeeCount: 1,
      })),
      enterpriseMessagesList: vi.fn(async () => []),
      enterpriseMessageSend: vi.fn(),
    });

    const view = render(<App />);
    fireEvent.click(screen.getByRole('button', { name: 'simulate-enterprise-consult-peer-otto' }));
    expect(await screen.findByRole('dialog', { name: '双方 Otto 协商' })).toBeTruthy();

    harness.organizationFeatures.current.atoa = false;
    view.rerender(<App />);

    await waitFor(() => {
      expect(screen.queryByRole('dialog', { name: '双方 Otto 协商' })).toBeNull();
    });
    expect(window.otto.enterpriseMessageSend).not.toHaveBeenCalled();
  });
});
