/**
 * @license Copyright 2026 Otto SPDX-License-Identifier: Apache-2.0
 */

import { cleanup, fireEvent, render, screen } from '@testing-library/react';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { App } from './App.js';
import type { EnterpriseAccount } from '../preload/index.js';
import { uiModeStorageKey } from './uiModePreference.js';

const harness = vi.hoisted(() => ({
  auth: { current: null as unknown },
  storeActions: {
    cancel: vi.fn(),
    clearError: vi.fn(),
    createSession: vi.fn(),
    deleteSession: vi.fn(),
    launchAgentProfile: vi.fn(),
    launchAgentProfileWithPrompt: vi.fn(),
    postSystemNote: vi.fn(),
    renameSession: vi.fn(),
    respondToolConfirmation: vi.fn(),
    selectSession: vi.fn(),
    sendMessage: vi.fn(),
    setModel: vi.fn(),
  },
  settingsActions: {
    clearExportMessage: vi.fn(),
    exportConversation: vi.fn(),
  },
  updateActions: { silentCheck: vi.fn() },
  productActions: {
    addFriend: vi.fn(),
    clearError: vi.fn(),
    confirmPendingAutoSkill: vi.fn(),
    createSchedule: vi.fn(),
    deleteSchedule: vi.fn(),
    refreshPendingAutoSkills: vi.fn(),
    rejectPendingAutoSkill: vi.fn(),
    selectDate: vi.fn(),
  },
}));

vi.mock('./state/useEnterpriseAuth.js', () => ({
  useEnterpriseAuth: () => harness.auth.current,
}));

vi.mock('./state/useOttoStore.js', () => ({
  useOttoStore: () => ({
    state: {
      connection: 'connected',
      sessions: {
        session_1: {
          sessionId: 'session_1',
          title: 'Test',
          status: 'idle',
          messageCount: 1,
          updatedAt: '2026-08-11T00:00:00.000Z',
        },
      },
      sessionIds: ['session_1'],
      activeSessionId: 'session_1',
      messages: { session_1: [] },
      models: [{ id: 'test-model', name: 'Test model' }],
      modelsLoaded: true,
      sessionsLoaded: true,
      currentModel: 'test-model',
      slashCommands: [],
      lastError: null,
      queuedCounts: {},
      pendingCreateRequestId: null,
      unreadSessions: [],
    },
    actions: harness.storeActions,
  }),
  groupSessions: () => [],
  selectSortedSessions: () => [],
}));

vi.mock('./state/useSettingsData.js', () => ({
  useSettingsData: () => ({
    state: { exportMessage: null },
    actions: harness.settingsActions,
  }),
}));

vi.mock('./state/useSoftwareUpdate.js', () => ({
  useSoftwareUpdate: () => ({
    state: { badgeVisible: false },
    actions: harness.updateActions,
  }),
}));

vi.mock('./state/useProductWorkspace.js', () => ({
  useProductWorkspace: () => ({
    state: {
      workspace: null,
      schedules: [],
      pendingAutoSkills: [],
      lastAutoSkillAction: null,
      selectedDate: '2026-08-11',
      error: null,
    },
    actions: harness.productActions,
  }),
}));

vi.mock('./state/centralEnterpriseIdentity.js', () => ({
  resolveCentralEnterpriseIdentity: () => ({
    edition: 'personal',
    role: 'member',
    profiles: [],
  }),
}));

vi.mock('./agents/departmentAgents.js', () => ({
  setAutoGeneratedAgentProfiles: vi.fn(),
}));

vi.mock('./components/EnterpriseLoginPage.js', () => ({
  EnterpriseLoginPage: () => <div data-testid="login-page" />,
}));

vi.mock('./components/Sidebar.js', () => ({
  Sidebar: ({ onOpenHub }: { onOpenHub: () => void }) => (
    <button type="button" onClick={onOpenHub}>open-preferences</button>
  ),
}));

vi.mock('./components/ChatView.js', () => ({
  ChatView: () => <main data-testid="chat-view" />,
}));

vi.mock('./components/RightPanel.js', () => ({
  RightPanel: () => <aside data-testid="work-panel" />,
}));

vi.mock('./components/ParkServicesPlugin.js', () => ({
  ParkServicesPlugin: () => null,
}));

vi.mock('./components/UiModeGuide.js', () => ({
  UiModeGuide: ({ onSelect }: { onSelect: (mode: 'conversational' | 'work') => void }) => (
    <div data-testid="ui-mode-guide">
      <button type="button" onClick={() => onSelect('conversational')}>choose-conversational</button>
      <button type="button" onClick={() => onSelect('work')}>choose-work</button>
    </div>
  ),
}));

vi.mock('./components/SettingsHubPage.js', () => ({
  SettingsHubPage: ({
    uiMode,
    onUiModeChange,
  }: {
    uiMode: 'conversational' | 'work';
    onUiModeChange: (mode: 'conversational' | 'work') => void;
  }) => (
    <section data-testid="settings-hub" data-ui-mode={uiMode}>
      <button type="button" onClick={() => onUiModeChange('conversational')}>settings-conversational</button>
      <button type="button" onClick={() => onUiModeChange('work')}>settings-work</button>
    </section>
  ),
}));

vi.mock('./components/WhatsNewDialog.js', () => ({
  WhatsNewDialog: () => <div data-testid="whats-new" />,
}));

vi.mock('./components/ProactiveToast.js', () => ({
  ProactiveToast: () => null,
}));

const accountA: EnterpriseAccount = {
  id: 'account-a',
  organizationId: 'personal-a',
  organizationName: 'Personal',
  accountType: 'personal',
  employeeId: null,
  username: 'account-a',
  phone: null,
  name: 'Alice',
  role: null,
  department: null,
  positionId: null,
  positionTitle: null,
  isAdmin: false,
  status: 'active',
  tags: [],
  createdAt: '2026-08-11T00:00:00.000Z',
  updatedAt: '2026-08-11T00:00:00.000Z',
};

function authFor(account: EnterpriseAccount | null, status: 'loading' | 'signed-out' | 'signed-in') {
  return {
    state: {
      status,
      account,
      serverUrl: 'https://enterprise.example.com/',
      registrationIntent: null,
      busy: false,
      error: null,
    },
    actions: {
      loginWithPassword: vi.fn(),
      requestLoginCode: vi.fn(),
      loginWithSms: vi.fn(),
      requestRegistrationCode: vi.fn(),
      register: vi.fn(),
      clearError: vi.fn(),
      joinEnterprise: vi.fn(),
      logout: vi.fn(),
    },
  };
}

function preferenceKey(account: EnterpriseAccount): string {
  return uiModeStorageKey({
    serverUrl: 'https://enterprise.example.com/',
    organizationId: account.organizationId,
    accountId: account.id,
  });
}

beforeEach(() => {
  localStorage.clear();
  harness.auth.current = authFor(accountA, 'signed-in');
  Object.defineProperty(window, 'otto', {
    configurable: true,
    writable: true,
    value: {
      ...window.otto,
      autoGeneratedAgentProfiles: vi.fn(() => new Promise(() => undefined)),
      onMenu: vi.fn(() => vi.fn()),
      onNotificationSessionOpen: vi.fn(() => vi.fn()),
    } as unknown as Window['otto'],
  });
});

afterEach(() => {
  cleanup();
  vi.clearAllMocks();
});

describe('App UI mode integration', () => {
  it('shows boot and login states without entering the workspace', () => {
    harness.auth.current = authFor(null, 'loading');
    const view = render(<App />);
    expect(screen.getByRole('status')).toBeTruthy();

    harness.auth.current = authFor(null, 'signed-out');
    view.rerender(<App />);
    expect(screen.getByTestId('login-page')).toBeTruthy();
  });

  it('starts first-time users in conversational mode and persists their work UI choice', () => {
    render(<App />);

    const app = document.querySelector<HTMLElement>('.otto-app');
    expect(app?.dataset.uiMode).toBe('conversational');
    expect(screen.getByTestId('ui-mode-guide')).toBeTruthy();
    expect(screen.queryByTestId('work-panel')).toBeNull();
    expect(screen.queryByTestId('whats-new')).toBeNull();

    fireEvent.click(screen.getByRole('button', { name: 'choose-work' }));

    expect(app?.dataset.uiMode).toBe('work');
    expect(screen.getByTestId('work-panel')).toBeTruthy();
    expect(screen.queryByTestId('ui-mode-guide')).toBeNull();
    expect(screen.getByTestId('whats-new')).toBeTruthy();
    expect(localStorage.getItem(preferenceKey(accountA))).toBe('work');
  });

  it('restores work UI and switches back from settings without touching account scope', () => {
    localStorage.setItem(preferenceKey(accountA), 'work');
    render(<App />);

    expect(screen.getByTestId('work-panel')).toBeTruthy();
    fireEvent.click(screen.getByRole('button', { name: 'open-preferences' }));
    expect(screen.getByTestId('settings-hub').dataset.uiMode).toBe('work');

    fireEvent.click(screen.getByRole('button', { name: 'settings-conversational' }));
    expect(screen.queryByTestId('work-panel')).toBeNull();
    expect(localStorage.getItem(preferenceKey(accountA))).toBe('conversational');
  });

  it('does not reuse one account UI preference for another account', () => {
    localStorage.setItem(preferenceKey(accountA), 'work');
    const view = render(<App />);
    expect(document.querySelector<HTMLElement>('.otto-app')?.dataset.uiMode).toBe('work');

    const accountB = {
      ...accountA,
      id: 'account-b',
      organizationId: 'personal-b',
      username: 'account-b',
      name: 'Bob',
    };
    harness.auth.current = authFor(accountB, 'signed-in');
    view.rerender(<App />);

    expect(document.querySelector<HTMLElement>('.otto-app')?.dataset.uiMode).toBe('conversational');
    expect(screen.getByTestId('ui-mode-guide')).toBeTruthy();
    expect(localStorage.getItem(preferenceKey(accountB))).toBeNull();
  });
});
