/**
 * @license
 * Copyright 2025 Otto
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * 顶层 App。单窗布局（docs/otto-desktop-ui-spec.md 为唯一基准）：
 *   左 Sidebar（会话列表 + 来源徽章） + 主 ChatView（顶栏/消息流/工具卡/输入区）。
 *
 * 飞书与本地会话共用同一聊天面（Issue #6 在 Sidebar/ChatView 内联实现：
 * 源徽章 + 顶栏「飞书·实时同步」指示），不再有独立 tab。
 * 状态/传输走 useOttoStore（preload WS ↔ otto-server，协议见 packages/server/src/protocol.ts）。
 *
 * 已接：会话分组列表（今天/昨天）、选择/新建会话、发消息（乐观渲染）、模型选择、
 *       流式回复、工具调用卡（含 diff）、错误 toast、setup/BYO-key 图形引导（Issue #7，
 *       SetupPanel 完整向导 + save_custom_model 落盘闭环）、断连/重连横幅、流式停止。
 * 待办：附件入站；slash 命令面板；「查看全部对话」检索视图（onViewAll 仍为空 TODO）。
 */

import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import './styles/tokens.css';
import './styles/app.css';
import type {
  MessageSource,
  ToolCall,
  ToolConfirmationResponsePayload,
} from 'otto-server';
import {
  useOttoStore,
  groupSessions,
  selectSortedSessions,
} from './state/useOttoStore.js';
import type { Attachment } from './state/useOttoStore.js';
import { Sidebar } from './components/Sidebar.js';
import { ChatView } from './components/ChatView.js';
import { SLASH_COMMANDS } from './components/Composer.js';
import {
  mergeServerCommands,
  buildHelpMarkdown,
} from './components/SlashCommands.js';
import { RightPanel } from './components/RightPanel.js';
import { UiModeGuide } from './components/UiModeGuide.js';
import { ParkServicesPlugin } from './components/ParkServicesPlugin.js';
import { AllConversations } from './components/AllConversations.js';
import { AgentGallery } from './components/AgentGallery.js';
import { SetupPanel } from './setup/SetupPanel.js';
import type { SaveCustomModelPayload } from './setup/presets.js';
import * as transport from './transport.js';
import { useSettingsData } from './state/useSettingsData.js';
import { useSoftwareUpdate } from './state/useSoftwareUpdate.js';
import { SettingsHubPage, type TabId as HubTabId } from './components/SettingsHubPage.js';
import { WhatsNewDialog } from './components/WhatsNewDialog.js';
import { FirstRunGuide } from './components/FirstRunGuide.js';
import { ProactiveToast } from './components/ProactiveToast.js';
import { useProductWorkspace } from './state/useProductWorkspace.js';
import { DayAgenda } from './components/DayAgenda.js';
import { SkillZonePage } from './components/SkillZonePage.js';
import { EnterpriseLoginPage } from './components/EnterpriseLoginPage.js';
import { AccountManagementPage } from './components/AccountManagementPage.js';
import { OrganizationPage } from './components/OrganizationPage.js';
import { InboxPage } from './components/InboxPage.js';
import { WorkPage } from './components/WorkPage.js';
import { useEnterpriseAuth } from './state/useEnterpriseAuth.js';
import type {
  EnterpriseAccount,
  EnterpriseAtoaInboxMessage,
  EnterpriseDirectMessage,
  EnterpriseFederationAtoaTask,
  EnterpriseFederationContact,
  EnterpriseOrganizationView,
} from '../preload/index.js';
import { askLocalPeerOtto } from './peerOttoRunner.js';
import {
  AtoaPermissionDialog,
  type AtoaPermissionRequest,
} from './components/AtoaPermissionDialog.js';
import type {
  AtoaPeerIdentity,
  AtoaPermissionDecision,
} from './enterpriseAtoaCoordinator.js';
import { processEnterpriseAtoaRequest } from './enterpriseAtoaCoordinator.js';
import { collectAuthorizedAtoaContext } from './a2aContext.js';
import { buildEnterpriseKnowledgePromptContext } from './enterpriseKnowledgePromptContext.js';
import { AtoaConsultDialog } from './components/AtoaConsultDialog.js';
import { executeEnterpriseCollaborationRelay } from './enterpriseCollaborationRelay.js';
import {
  EnterpriseUnreadNotificationTracker,
  type EnterpriseUnreadCounts,
} from './enterpriseUnreadNotifications.js';
import { resolveCentralEnterpriseIdentity } from './state/centralEnterpriseIdentity.js';
import {
  INTERNAL_TEST_ACCESS_ENABLED,
  INTERNAL_TEST_ACCOUNT,
  resolveEnterpriseAccessMode,
} from './internal-test-access.js';
import {
  setAutoGeneratedAgentProfiles,
  type AgentProfile,
} from './agents/departmentAgents.js';
import {
  DEFAULT_UI_MODE,
  readUiModePreference,
  writeUiModePreference,
  type UiMode,
} from './uiModePreference.js';
import {
  buildCustomAgentKickoff,
  createCustomAgent,
  customAgentStorageKey,
  parseCustomAgents,
  type CustomAgentDefinition,
  type CustomAgentDraft,
} from './customAgents.js';

/** 启动后静默检查更新的延迟：让 server 连接 / 首屏渲染先跑完，不抢启动窗口。 */
const SILENT_UPDATE_CHECK_DELAY_MS = 15_000;
/** 企业私聊后台未读轮询；只取摘要，不把消息提前标已读。 */
const ENTERPRISE_UNREAD_POLL_INTERVAL_MS = 5_000;
const ENTERPRISE_PRESENCE_HEARTBEAT_MS = 20_000;

/** 主内容区当前视图：对话 / 专家 / 工作台 / 组织架构 / 我的消息 / 我的工作 / 设置——均为整页。 */
type MainView = 'chat' | 'agents' | 'workspace' | 'settings' | 'hub' | 'agenda' | 'skillzone' | 'accounts'
  | 'organization' | 'inbox' | 'work';

type PendingToolConsult = {
  member: EnterpriseOrganizationView['members'][number];
  question: string;
};

export function App(): React.JSX.Element {
  const auth = useEnterpriseAuth();
  const accessMode = resolveEnterpriseAccessMode({
    internalTestAccessEnabled: INTERNAL_TEST_ACCESS_ENABLED,
    authStatus: auth.state.status,
    hasAccount: Boolean(auth.state.account),
    hasRegistrationIntent: Boolean(auth.state.registrationIntent),
  });

  if (accessMode === 'internal-workspace') {
    return <OttoWorkspaceApp account={INTERNAL_TEST_ACCOUNT} serverUrl="internal://test" />;
  }
  if (accessMode === 'booting') {
    return (
      <div className="otto-auth-boot" role="status">
        <span>O</span>
        <div><strong>OTTO</strong><small>正在验证企业身份…</small></div>
      </div>
    );
  }
  if (accessMode === 'registration' || accessMode === 'login' || !auth.state.account) {
    return (
      <EnterpriseLoginPage
        initialServerUrl={auth.state.serverUrl}
        initialInviteCode={auth.state.registrationIntent?.inviteCode}
        busy={auth.state.busy}
        error={auth.state.error}
        onPasswordLogin={auth.actions.loginWithPassword}
        onRequestLoginCode={auth.actions.requestLoginCode}
        onSmsLogin={auth.actions.loginWithSms}
        onRequestRegistrationCode={auth.actions.requestRegistrationCode}
        onRegister={auth.actions.register}
        onClearError={auth.actions.clearError}
      />
    );
  }
  return (
    <OttoWorkspaceApp
      key={`${auth.state.serverUrl}:${auth.state.account.id}:${auth.state.account.organizationId}`}
      account={auth.state.account}
      serverUrl={auth.state.serverUrl}
      onJoinEnterprise={auth.actions.joinEnterprise}
      onLogout={auth.actions.logout}
    />
  );
}

function OttoWorkspaceApp({
  account,
  serverUrl,
  onJoinEnterprise,
  onLogout,
}: {
  account: EnterpriseAccount;
  serverUrl?: string;
  onJoinEnterprise?: (input: { inviteCode: string }) => Promise<void>;
  onLogout?: () => Promise<void>;
}): React.JSX.Element {
  const { state, actions } = useOttoStore({
    enterpriseOrganizationId: account.accountType === 'personal'
      ? null
      : account.organizationId,
  });
  const settingsData = useSettingsData();
  const softwareUpdate = useSoftwareUpdate();
  const product = useProductWorkspace();
  const [enterpriseUnreadCounts, setEnterpriseUnreadCounts] = useState<EnterpriseUnreadCounts>({});
  const centralIdentity = useMemo(
    () => resolveCentralEnterpriseIdentity(account),
    [account],
  );
  const edition = centralIdentity.edition;
  const customAgentsKey = useMemo(
    () => customAgentStorageKey(account.organizationId, account.id),
    [account.id, account.organizationId],
  );
  const [customAgents, setCustomAgents] = useState<CustomAgentDefinition[]>(() => {
    try {
      return parseCustomAgents(localStorage.getItem(customAgentsKey));
    } catch {
      return [];
    }
  });
  useEffect(() => {
    try {
      setCustomAgents(parseCustomAgents(localStorage.getItem(customAgentsKey)));
    } catch {
      setCustomAgents([]);
    }
  }, [customAgentsKey]);
  const permissionResolver = useRef<((decision: AtoaPermissionDecision) => void) | null>(null);
  const [pendingAtoaPermission, setPendingAtoaPermission] = useState<AtoaPermissionRequest | null>(null);
  const federationAtoaContextCache = useRef(new Map<string, Awaited<
    ReturnType<typeof collectAuthorizedAtoaContext>
  >>());
  const requestAtoaPermission = useCallback(
    async (
      request: Omit<AtoaPermissionRequest, 'messages'>,
      authorizedMessages?: EnterpriseDirectMessage[],
    ): Promise<AtoaPermissionDecision> => {
      const messages = authorizedMessages ??
        await window.otto.enterpriseMessagesList(request.peer.id);
      return new Promise((resolve) => {
        // 服务器一次只 claim 一条；若界面状态异常叠加，旧请求按拒绝收口。
        permissionResolver.current?.({ kind: 'deny' });
        permissionResolver.current = resolve;
        setPendingAtoaPermission({ ...request, messages });
      });
    },
    [],
  );
  const completeAtoaPermission = useCallback(
    (decision: AtoaPermissionDecision): void => {
      const resolve = permissionResolver.current;
      permissionResolver.current = null;
      setPendingAtoaPermission(null);
      resolve?.(decision);
    },
    [],
  );
  const toolConsultResolver = useRef<{
    resolve: (message: EnterpriseDirectMessage) => void;
    reject: (error: Error) => void;
  } | null>(null);
  const [pendingToolConsult, setPendingToolConsult] = useState<PendingToolConsult | null>(null);
  const requestToolConsult = useCallback(
    (
      member: EnterpriseOrganizationView['members'][number],
      question: string,
    ): Promise<EnterpriseDirectMessage> =>
      new Promise((resolve, reject) => {
        toolConsultResolver.current?.reject(new Error('已有一项双方 Otto 协商等待处理'));
        toolConsultResolver.current = { resolve, reject };
        setPendingToolConsult({ member, question });
      }),
    [],
  );
  const finishToolConsult = useCallback(
    (message: EnterpriseDirectMessage): void => {
      toolConsultResolver.current?.resolve(message);
      toolConsultResolver.current = null;
      setPendingToolConsult(null);
    },
    [],
  );
  const cancelToolConsult = useCallback((): void => {
    toolConsultResolver.current?.reject(new Error('用户取消了双方 Otto 协商'));
    toolConsultResolver.current = null;
    setPendingToolConsult(null);
  }, []);
  useEffect(
    () => () => {
      toolConsultResolver.current?.reject(new Error('账号已切换，双方 Otto 协商已取消'));
      toolConsultResolver.current = null;
    },
    [account.id],
  );

  useEffect(() => {
    if (account.accountType === 'personal') return undefined;
    let cancelled = false;
    let polling = false;
    let localUnreadCounts: EnterpriseUnreadCounts = {};
    const federationMarkers = new Map<string, string>();
    const tracker = new EnterpriseUnreadNotificationTracker({
      show: (payload) => window.otto.notificationShow(payload),
      markRead: (sessionId) => window.otto.notificationMarkRead(sessionId),
      onUnreadCountsChange: (counts) => { localUnreadCounts = counts; },
    });

    const poll = async (): Promise<void> => {
      if (polling || cancelled) return;
      polling = true;
      try {
        const [response, federationContacts] = await Promise.all([
          window.otto.enterpriseMessagesUnread(),
          window.otto.enterpriseFederationContacts().catch(
            () => [] as EnterpriseFederationContact[],
          ),
        ]);
        const notifications = Array.isArray(response) ? response : [];
        if (cancelled) return;
        await tracker.reconcile(notifications);
        const federationCounts: EnterpriseUnreadCounts = {};
        const activeFederationSessions = new Set<string>();
        for (const contact of federationContacts) {
          const sessionId = `enterprise:federation:${contact.id}`;
          if (contact.unreadCount <= 0) continue;
          activeFederationSessions.add(sessionId);
          federationCounts[sessionId] = contact.unreadCount;
          const marker = `${contact.lastMessageAt ?? ''}:${contact.unreadCount}`;
          if (federationMarkers.get(sessionId) === marker) continue;
          await window.otto.notificationShow({
            sessionId,
            source: 'enterprise',
            sender: contact.displayName,
            preview: '收到一条端到端加密的跨服务器消息',
          });
          federationMarkers.set(sessionId, marker);
        }
        for (const sessionId of [...federationMarkers.keys()]) {
          if (activeFederationSessions.has(sessionId)) continue;
          federationMarkers.delete(sessionId);
          await window.otto.notificationMarkRead(sessionId);
        }
        if (!cancelled) {
          setEnterpriseUnreadCounts({ ...localUnreadCounts, ...federationCounts });
        }
      } catch {
      } finally {
        polling = false;
      }
    };

    void poll();
    const timer = window.setInterval(() => void poll(), ENTERPRISE_UNREAD_POLL_INTERVAL_MS);
    return () => {
      cancelled = true;
      window.clearInterval(timer);
      setEnterpriseUnreadCounts({});
      for (const sessionId of federationMarkers.keys()) {
        void window.otto.notificationMarkRead(sessionId).catch(() => undefined);
      }
      federationMarkers.clear();
      void tracker.clear();
    };
  }, [account.accountType, account.id, account.organizationId]);

  useEffect(() => {
    if (account.accountType === 'personal') return undefined;
    let cancelled = false;
    const beat = async (): Promise<void> => {
      try {
        await window.otto.enterprisePresenceHeartbeat?.();
      } catch {
      }
    };

    void beat();
    const timer = window.setInterval(() => {
      if (!cancelled) void beat();
    }, ENTERPRISE_PRESENCE_HEARTBEAT_MS);
    return () => {
      cancelled = true;
      window.clearInterval(timer);
    };
  }, [account.accountType, account.id, account.organizationId]);

  const markEnterpriseDirectMessageRead = useCallback((peerAccountId: string): void => {
    const sessionId = `enterprise:message:${peerAccountId}`;
    setEnterpriseUnreadCounts((current) => {
      if (!current[sessionId]) return current;
      const next = { ...current };
      delete next[sessionId];
      return next;
    });
    void window.otto.notificationMarkRead(sessionId).catch(() => undefined);
  }, []);

  const markEnterpriseFederationMessageRead = useCallback((contactId: string): void => {
    const sessionId = `enterprise:federation:${contactId}`;
    setEnterpriseUnreadCounts((current) => {
      if (!current[sessionId]) return current;
      const next = { ...current };
      delete next[sessionId];
      return next;
    });
    void window.otto.notificationMarkRead(sessionId).catch(() => undefined);
  }, []);

  useEffect(() => {
    if (account.accountType === 'personal') return undefined;
    const processing = new Set<string>();
    const abortController = new AbortController();
    let polling = false;
    let cancelled = false;

    const handleRequest = async (
      request: EnterpriseAtoaInboxMessage & { peer?: AtoaPeerIdentity },
    ): Promise<void> => {
      if (processing.has(request.id)) return;
      processing.add(request.id);
      const notificationId = `enterprise:atoa:${request.id}`;
      void window.otto.notificationShow({
        sessionId: notificationId,
        source: 'atoa',
        sender: request.peer?.name ?? '企业同事',
        preview: '你的 Otto 收到一条企业协作请求，等待授权处理',
      }).catch(() => undefined);
      try {
        await processEnterpriseAtoaRequest({
          request,
          requestPermission: requestAtoaPermission,
          collectContext: (sources, authorizedMessageIds) =>
            collectAuthorizedAtoaContext({
              sources,
              authorizedMessageIds,
              peerAccountId: request.peerAccountId,
              currentAccountId: account.id,
              currentAccountName: account.name,
              peerName: request.peer?.name ?? '企业同事',
              listMessages: window.otto.enterpriseMessagesList,
              listKnowledge: () => window.otto.enterpriseKnowledgeList(),
              workLogRecent: window.otto.workLogRecent,
              schedules: product.state.schedules,
            }),
          askOtto: (input) =>
            askLocalPeerOtto({
              ...input,
              requestId: `a2a-${request.id}`,
              clientMessageId: `a2a-reply-${request.id}`,
              signal: abortController.signal,
            }),
          sendMessage: window.otto.enterpriseMessageSend,
          signal: abortController.signal,
        });
        void window.otto.notificationMarkRead(notificationId).catch(() => undefined);
      } catch {
        processing.delete(request.id);
        throw new Error('A2A 回复发送失败');
      }
    };

    const poll = async (): Promise<void> => {
      if (polling || cancelled) return;
      polling = true;
      try {
        const requests = await window.otto.enterpriseAtoaInbox();
        for (const request of requests) {
          if (cancelled) break;
          try {
            await handleRequest(request);
          } catch {
          }
        }
      } catch {
      } finally {
        polling = false;
      }
    };

    void poll();
    const timer = window.setInterval(() => void poll(), 8_000);
    return () => {
      cancelled = true;
      abortController.abort();
      permissionResolver.current?.({ kind: 'deny' });
      permissionResolver.current = null;
      window.clearInterval(timer);
    };
  }, [
    account.accountType,
    account.id,
    account.name,
    product.state.schedules,
    requestAtoaPermission,
  ]);

  useEffect(() => {
    if (account.accountType === 'personal') return undefined;
    const processing = new Set<string>();
    const abortController = new AbortController();
    const contextCache = federationAtoaContextCache.current;
    let cancelled = false;
    let polling = false;

    const taskKey = (task: EnterpriseFederationAtoaTask): string =>
      `${task.kind}:${task.contact.id}:${task.message.id}`;
    const contextKey = (
      task: Extract<EnterpriseFederationAtoaTask, { kind: 'proposal' | 'request' }>,
    ): string => `${task.contact.id}:${task.request.id}`;
    const peerIdentity = (
      task: EnterpriseFederationAtoaTask,
    ): AtoaPeerIdentity => ({
      id: task.contact.identity,
      name: task.contact.displayName,
      department: task.contact.deploymentDisplayName,
      positionTitle: '跨服务器联系人',
      role: null,
    });
    const collectContext = async (
      task: Extract<EnterpriseFederationAtoaTask, { kind: 'proposal' | 'request' }>,
      sources: AtoaPermissionDecision & { kind: 'allow' },
      messages: EnterpriseDirectMessage[],
    ) => collectAuthorizedAtoaContext({
      sources: sources.sources,
      authorizedMessageIds: sources.messageIds ?? [],
      peerAccountId: task.contact.identity,
      currentAccountId: account.id,
      currentAccountName: account.name,
      peerName: task.contact.displayName,
      listMessages: async () => messages,
      listKnowledge: () => window.otto.enterpriseKnowledgeList(),
      workLogRecent: window.otto.workLogRecent,
      schedules: product.state.schedules,
    });

    const processTask = async (
      task: EnterpriseFederationAtoaTask,
    ): Promise<void> => {
      const key = taskKey(task);
      if (processing.has(key)) return;
      processing.add(key);
      try {
        if (task.kind === 'grant') {
          await window.otto.enterpriseFederationAtoaDispatch({
            contactId: task.contact.id,
            decisionMessageId: task.message.id,
          });
          return;
        }

        const notificationId = `enterprise:federation-atoa:${task.message.id}`;
        await window.otto.notificationShow({
          sessionId: notificationId,
          source: 'atoa',
          sender: task.contact.displayName,
          preview: task.kind === 'proposal'
            ? '对方 Otto 请求一次性读取你明确选择的资料'
            : '已核验的一次性 A2A 请求正在等待本机处理',
        }).catch(() => undefined);

        const messages = await window.otto.enterpriseFederationMessagesList(
          task.contact.id,
          { markRead: false },
        );
        if (task.kind === 'proposal') {
          const decision = await requestAtoaPermission({
            peer: peerIdentity(task),
            payload: task.request,
          }, messages);
          if (decision.kind === 'deny') {
            await window.otto.enterpriseFederationAtoaDeny({
              contactId: task.contact.id,
              messageId: task.message.id,
            });
            await window.otto.notificationMarkRead(notificationId);
            return;
          }
          const allowedSources = task.request.requestedSources.length > 0
            ? decision.sources.filter((source) =>
                task.request.requestedSources.includes(source))
            : decision.sources;
          if (allowedSources.length === 0) {
            await window.otto.enterpriseFederationAtoaDeny({
              contactId: task.contact.id,
              messageId: task.message.id,
            });
            await window.otto.notificationMarkRead(notificationId);
            return;
          }
          const allowedDecision: AtoaPermissionDecision & { kind: 'allow' } = {
            ...decision,
            sources: allowedSources,
          };
          const context = await collectContext(task, allowedDecision, messages);
          await window.otto.enterpriseFederationAtoaApprove({
            contactId: task.contact.id,
            messageId: task.message.id,
            grantedSources: allowedSources,
          });
          contextCache.set(contextKey(task), context);
          await window.otto.notificationMarkRead(notificationId);
          return;
        }

        let context = contextCache.get(contextKey(task));
        if (!context) {
          let sources = task.grantedSources;
          let messageIds: string[] = [];
          if (task.needsCurrentChatSelection) {
            const repeatedDecision = await requestAtoaPermission({
              peer: peerIdentity(task),
              payload: task.request,
            }, messages);
            if (repeatedDecision.kind === 'deny') {
              await window.otto.enterpriseFederationAtoaRespond({
                contactId: task.contact.id,
                requestMessageId: task.message.id,
                answer: '对方取消了本次授权，Otto 未读取任何资料。',
                grantedSources: [],
              });
              await window.otto.notificationMarkRead(notificationId);
              return;
            }
            sources = repeatedDecision.sources.filter((source) =>
              task.grantedSources.includes(source));
            messageIds = repeatedDecision.messageIds ?? [];
          }
          context = await collectContext(task, {
            kind: 'allow',
            sources,
            messageIds,
          }, messages);
        }

        let answer: string;
        try {
          answer = await askLocalPeerOtto({
            question: task.request.question,
            workContext: context.context,
            mode: task.request.mode,
            initiatorProposal: task.request.initiatorProposal,
            requestId: `federation-a2a-${task.message.id}`,
            clientMessageId: `federation-a2a-reply-${task.message.id}`,
            signal: abortController.signal,
          });
        } catch {
          if (abortController.signal.aborted) return;
          answer = '本机 Otto 本次未能完成回答，请稍后重试或直接联系本人。';
        }
        await window.otto.enterpriseFederationAtoaRespond({
          contactId: task.contact.id,
          requestMessageId: task.message.id,
          answer,
          grantedSources: context.loadedSources,
        });
        contextCache.delete(contextKey(task));
        await window.otto.notificationMarkRead(notificationId);
      } catch {
        processing.delete(key);
      }
    };

    const poll = async (): Promise<void> => {
      if (polling || cancelled) return;
      polling = true;
      try {
        const tasks = await window.otto.enterpriseFederationAtoaTasks();
        for (const task of tasks) {
          if (cancelled) break;
          await processTask(task);
        }
      } catch {
      } finally {
        polling = false;
      }
    };

    void poll();
    const timer = window.setInterval(() => void poll(), 8_000);
    return () => {
      cancelled = true;
      abortController.abort();
      contextCache.clear();
      window.clearInterval(timer);
    };
  }, [
    account.accountType,
    account.id,
    account.name,
    product.state.schedules,
    requestAtoaPermission,
  ]);

  useEffect(() => {
    let cancelled = false;
    void window.otto.autoGeneratedAgentProfiles()
      .then((profiles) => {
        if (cancelled) return;
        setAutoGeneratedAgentProfiles(profiles);
      })
      .catch(() => {
        if (!cancelled) setAutoGeneratedAgentProfiles([]);
      });
    return () => { cancelled = true; };
  }, [account]);

  useEffect(() => {
    const timer = window.setTimeout(
      () => softwareUpdate.actions.silentCheck(),
      SILENT_UPDATE_CHECK_DELAY_MS,
    );
    return () => window.clearTimeout(timer);
  }, [softwareUpdate.actions]);

  // —— 统一消息中心：会话历史、未读状态与企业通知 ——
  const [allConvOpen, setAllConvOpen] = useState(false);
  const [mainView, setMainView] = useState<MainView>('chat');
  const uiModeScope = useMemo(() => ({
    serverUrl,
    organizationId: account.organizationId,
    accountId: account.id,
  }), [account.id, account.organizationId, serverUrl]);
  const [savedUiMode, setSavedUiMode] = useState<UiMode | null>(
    () => readUiModePreference(uiModeScope),
  );
  const uiMode = savedUiMode ?? DEFAULT_UI_MODE;
  const selectUiMode = useCallback((nextMode: UiMode): void => {
    writeUiModePreference(uiModeScope, nextMode);
    setSavedUiMode(nextMode);
  }, [uiModeScope]);
  const [organizationRefreshRevision, setOrganizationRefreshRevision] = useState(0);
  const [enterpriseDirectChatOpenRequest, setEnterpriseDirectChatOpenRequest] = useState<{
    peerAccountId: string;
    requestId: number;
  }>();
  const [enterpriseFederationChatOpenRequest, setEnterpriseFederationChatOpenRequest] = useState<{
    contactId: string;
    requestId: number;
  }>();
  const openNotificationSession = useCallback((sessionId: string): void => {
    const federationPrefix = 'enterprise:federation:';
    if (sessionId.startsWith(federationPrefix)) {
      const contactId = sessionId.slice(federationPrefix.length);
      if (!contactId) return;
      setMainView('inbox');
      setEnterpriseFederationChatOpenRequest((current) => ({
        contactId,
        requestId: (current?.requestId ?? 0) + 1,
      }));
      return;
    }
    const prefix = 'enterprise:message:';
    if (!sessionId.startsWith(prefix)) return;
    const peerAccountId = sessionId.slice(prefix.length);
    if (!peerAccountId) return;
    setMainView('organization');
    setEnterpriseDirectChatOpenRequest((current) => ({
      peerAccountId,
      requestId: (current?.requestId ?? 0) + 1,
    }));
  }, []);
  useEffect(
    () => window.otto.onNotificationSessionOpen(openNotificationSession),
    [openNotificationSession],
  );
  // 打开「设置与诊断中心」时默认停在哪个 tab（斜杠命令 /doctor /memory /skills 直达用）。
  const [hubInitialTab, setHubInitialTab] = useState<HubTabId>('prefs');
  const openHub = (tab: HubTabId = 'prefs'): void => {
    setHubInitialTab(tab);
    setMainView('hub');
  };
  useEffect(() => {
    if (mainView !== 'hub') return;
    const closeOnEscape = (event: KeyboardEvent): void => {
      if (event.key !== 'Escape') return;
      event.preventDefault();
      setMainView('chat');
    };
    window.addEventListener('keydown', closeOnEscape);
    return () => window.removeEventListener('keydown', closeOnEscape);
  }, [mainView]);
  const setupOpen = mainView === 'settings';
  const [saving, setSaving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const autoFloated = useRef(false);
  const [exemptActive, setExemptActive] = useState(false);
  useEffect(() => {
    try {
      const exempt = localStorage.getItem('otto_exempt_code');
      if (exempt === 'OTTO-DEV-2026') {
        setExemptActive(true);
      }
    } catch {
    }
  }, []);
  useEffect(() => {
    if (
      !autoFloated.current &&
      !exemptActive &&
      state.connection === 'connected' &&
      state.modelsLoaded &&
      state.models.length === 0
    ) {
      autoFloated.current = true;
      setMainView('settings');
    }
  }, [
    exemptActive,
    state.connection,
    state.modelsLoaded,
    state.models.length,
    product.state.workspace?.context.edition,
  ]);

  useEffect(() => {
    if (!setupOpen || !saving) return;
    const off = transport.onFrame((frame) => {
      if (frame.type === 'models_list') {
        setSaving(false);
        setSaveError(null);
        setMainView('chat');
      } else if (
        frame.type === 'error' &&
        frame.payload.code === 'save_failed'
      ) {
        setSaving(false);
        setSaveError(frame.payload.message || '保存失败，请重试');
      }
    });
    return off;
  }, [setupOpen, saving]);

  const closeSetup = (): void => {
    setMainView('chat');
    setSaving(false);
    setSaveError(null);
  };

  const handleSaveModel = (payload: SaveCustomModelPayload): void => {
    setSaveError(null);
    setSaving(true);
    transport.send({ type: 'save_custom_model', payload });
  };

  const handleDeleteModel = (id: string): void => {
    transport.send({ type: 'delete_custom_model', payload: { id } });
  };

  const bootstrappedRef = useRef(false);
  useEffect(() => {
    if (state.connection !== 'connected' || !state.sessionsLoaded) return;
    if (state.sessionIds.length === 0) {
      if (!bootstrappedRef.current) {
        bootstrappedRef.current = true;
        actions.createSession();
      }
      return;
    }
    bootstrappedRef.current = true;
    if (!state.activeSessionId) {
      actions.selectSession(state.sessionIds[0]);
    }
  }, [
    state.connection,
    state.sessionsLoaded,
    state.sessionIds,
    state.activeSessionId,
    actions,
  ]);

  useEffect(() => {
    const off = transport.onMenu((action) => {
      if (action === 'new-chat') {
        setMainView('chat');
        actions.createSession();
      } else if (action === 'open-settings') {
        setMainView('settings');
      }
    });
    return off;
  }, [actions, edition]);

  const groups = useMemo(() => groupSessions(state), [state]);

  const activeSession = state.activeSessionId
    ? state.sessions[state.activeSessionId] ?? null
    : null;
  const activeMessages = state.activeSessionId
    ? state.messages[state.activeSessionId] ?? []
    : [];

  const busy = activeSession?.status === 'thinking' || activeSession?.status === 'streaming';

  const handleRegenerate = (messageId?: string): void => {
    let target: (typeof activeMessages)[number] | undefined;
    const idx = messageId
      ? activeMessages.findIndex((m) => m.id === messageId)
      : -1;
    if (idx >= 0) {
      for (let i = idx; i >= 0; i--) {
        if (activeMessages[i].role === 'user') {
          target = activeMessages[i];
          break;
        }
      }
    }
    if (!target) {
      target = [...activeMessages].reverse().find((m) => m.role === 'user');
    }
    if (!target) return;
    const text = target.content
      .map((p) => (p.type === 'text' ? p.value : ''))
      .join('')
      .trim();
    if (text) actions.sendMessage(text, target.source);
  };

  const handleSend = (
    text: string,
    source: MessageSource,
    attachments?: Attachment[],
  ): void => {
    const sendWithEnterpriseKnowledge = async (): Promise<void> => {
      let authorizedContext = '';
      if (edition === 'enterprise' && text.trim()) {
        try {
          const knowledge = await Promise.race([
            window.otto.enterpriseKnowledgeList({ query: text.trim() }),
            new Promise<never>((_, reject) => {
              window.setTimeout(() => reject(new Error('enterprise knowledge lookup timeout')), 1_200);
            }),
          ]);
          authorizedContext = buildEnterpriseKnowledgePromptContext(knowledge);
        } catch {
          actions.postSystemNote('企业知识检索暂不可用；本轮将继续回答，但未附加企业知识上下文。');
        }
      }
      actions.sendMessage(text, source, attachments, undefined, authorizedContext);
    };
    void sendWithEnterpriseKnowledge();
  };

  const handleNewChat = (): void => {
    setMainView('chat');
    const empty = state.sessionIds
      .map((id) => state.sessions[id])
      .find(
        (s) =>
          Boolean(s) &&
          s.messageCount === 0 &&
          (state.messages[s.sessionId]?.length ?? 0) === 0,
      );
    if (empty) {
      actions.selectSession(empty.sessionId);
      return;
    }
    actions.createSession();
  };

  const handleClearContext = (): void => {
    setMainView('chat');
    actions.createSession();
  };

  const handleLaunchProfile = (profile: AgentProfile): void => {
    setMainView('chat');
    actions.launchAgentProfile(profile.name, profile.id);
  };

  const persistCustomAgents = (nextAgents: CustomAgentDefinition[]): void => {
    try {
      localStorage.setItem(customAgentsKey, JSON.stringify(nextAgents));
    } catch {
      throw new Error('本机存储不可用，专家未保存');
    }
    setCustomAgents(nextAgents);
  };

  const handleLaunchCustomAgent = (agent: CustomAgentDefinition): void => {
    setMainView('chat');
    actions.launchAgentProfileWithPrompt(
      agent.name,
      edition === 'enterprise' ? 'otto-enterprise-work' : 'otto-personal',
      buildCustomAgentKickoff(agent, {
        edition,
        organizationName: account.organizationName,
        department: account.department,
        positionTitle: account.positionTitle,
      }),
    );
  };

  const handleCreateCustomAgent = (draft: CustomAgentDraft): void => {
    if (customAgents.length >= 12) {
      throw new Error('最多保存 12 个自定义专家，请先删除一个');
    }
    const agent = createCustomAgent(draft, {
      id: `custom-${crypto.randomUUID()}`,
      now: new Date().toISOString(),
    });
    if (customAgents.some(
      (item) => item.name.localeCompare(agent.name, 'zh-CN', { sensitivity: 'base' }) === 0,
    )) {
      throw new Error('已有同名专家，请换一个名称');
    }
    persistCustomAgents([agent, ...customAgents]);
    handleLaunchCustomAgent(agent);
  };

  const handleDeleteCustomAgent = (agentId: string): void => {
    persistCustomAgents(customAgents.filter((agent) => agent.id !== agentId));
  };

  const handleToolConfirmation = useCallback(
    (
      callId: string,
      outcome: 'approved' | 'rejected' | 'always_approve',
      payload?: ToolConfirmationResponsePayload,
      tool?: ToolCall,
    ): void => {
      if (
        outcome !== 'approved' ||
        tool?.confirmationDetails?.rootCommand !== 'enterprise_collaboration'
      ) {
        actions.respondToolConfirmation(callId, outcome, payload);
        return;
      }

      void executeEnterpriseCollaborationRelay(tool.parameters, account, {
        getOrganizationView: window.otto.enterpriseOrganizationView,
        sendMessage: window.otto.enterpriseMessageSend,
        requestConsult: requestToolConsult,
        updateAccount: window.otto.enterpriseAccountUpdate,
      })
        .then((result) => {
          actions.respondToolConfirmation(callId, 'approved', {
            newContent: JSON.stringify(result),
          });
        })
        .catch((reason: unknown) => {
          const error = reason instanceof Error ? reason.message : String(reason);
          actions.respondToolConfirmation(callId, 'approved', {
            newContent: JSON.stringify({ ok: false, error }),
          });
        });
    },
    [account, actions, requestToolConsult],
  );

  const openModelSettings = (): void => {
    setMainView('settings');
  };

  const selectedDate = product.state.selectedDate ?? new Date().toISOString().slice(0, 10);
  const selectedSchedules = useMemo(
    () => product.state.schedules.filter((item) => {
      const date = new Date(item.startAt);
      if (Number.isNaN(date.getTime())) return false;
      const key = `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
      return key === selectedDate;
    }),
    [product.state.schedules, selectedDate],
  );

  const slashCommands = useMemo(
    () => mergeServerCommands(SLASH_COMMANDS, state.slashCommands ?? []),
    [state.slashCommands],
  );

  const handleShowHelp = (): void => {
    actions.postSystemNote(buildHelpMarkdown(slashCommands));
  };

  return (
    <div className="otto-app" data-connection={state.connection} data-ui-mode={uiMode}>
      <Sidebar
        groups={groups}
        activeSessionId={state.activeSessionId}
        hubActive={mainView === 'hub'}
        activeView={mainView}
        accountManagementActive={mainView === 'accounts'}
        updateBadge={softwareUpdate.state.badgeVisible}
        onSelect={(id) => {
          setMainView('chat');
          actions.selectSession(id);
        }}
        onNewChat={handleNewChat}
        onOpenHub={() => openHub('prefs')}
        onOpenAccounts={() => setMainView('accounts')}
        onNavigate={(view) => {
          if (view === 'hub') openHub('prefs');
          else setMainView(view);
        }}
        onViewAll={() => setAllConvOpen(true)}
        onRename={actions.renameSession}
        onDelete={actions.deleteSession}
        enterpriseAccount={account}
        enterpriseUnreadCounts={enterpriseUnreadCounts}
        onJoinEnterprise={onJoinEnterprise}
        onLogout={onLogout}
        unreadSessions={state.unreadSessions}
      />
      <ParkServicesPlugin />

      {mainView === 'organization' ? (
        <OrganizationPage
          enterpriseAccount={account}
          schedules={product.state.schedules}
          organizationRefreshRevision={organizationRefreshRevision}
          enterpriseUnreadCounts={enterpriseUnreadCounts}
          enterpriseDirectChatOpenRequest={enterpriseDirectChatOpenRequest}
          onMessageRead={markEnterpriseDirectMessageRead}
          onBack={() => setMainView('chat')}
        />
      ) : mainView === 'inbox' ? (
        <InboxPage
          enterpriseAccount={account}
          enterpriseUnreadCounts={enterpriseUnreadCounts}
          federationContactOpenRequest={enterpriseFederationChatOpenRequest}
          onFederationMessageRead={markEnterpriseFederationMessageRead}
          onOpenDirectChat={(peerId) => {
            setMainView('organization');
            setEnterpriseDirectChatOpenRequest((cur) => ({
              peerAccountId: peerId,
              requestId: (cur?.requestId ?? 0) + 1,
            }));
          }}
          onMessageRead={markEnterpriseDirectMessageRead}
          onBack={() => setMainView('chat')}
        />
      ) : mainView === 'work' ? (
        <WorkPage
          schedules={product.state.schedules}
          selectedDate={selectedDate}
          onSelectDate={product.actions.selectDate}
          onCreateSchedule={product.actions.createSchedule}
          onDeleteSchedule={product.actions.deleteSchedule}
          onBack={() => setMainView('chat')}
        />
      ) : mainView === 'settings' ? (
        <SetupPanel
          models={state.models}
          saving={saving}
          saveError={saveError}
          onClose={closeSetup}
          onSave={handleSaveModel}
          onDeleteModel={handleDeleteModel}
        />
      ) : mainView === 'accounts' && edition === 'enterprise' && account.isAdmin ? (
        <AccountManagementPage
          currentAccount={account}
          onBack={() => setMainView('chat')}
          onOrganizationChanged={() => setOrganizationRefreshRevision((value) => value + 1)}
        />
      ) : mainView === 'agents' ? (
        <AgentGallery
          mode={edition}
          profiles={centralIdentity.profiles}
          onLaunch={handleLaunchProfile}
          onBack={() => setMainView('chat')}
        />
      ) : mainView === 'workspace' ? (
        <section className="otto-workspace-page" aria-label="工作台">
          <header className="otto-workspace-page__head">
            <div>
              <div className="otto-workspace-page__title">专家与工作区</div>
              <div className="otto-workspace-page__subtitle">专家、常用命令、文档、企业记忆与工作日志</div>
            </div>
            <button type="button" className="otto-workspace-page__back" onClick={() => setMainView('chat')}>
              返回对话
            </button>
          </header>
          <RightPanel
            presentation="page"
            busy={busy}
            mode={edition}
            enterpriseRole={centralIdentity.role}
            enterpriseOrganizationId={account.organizationId}
            workspace={product.state.workspace}
            profiles={centralIdentity.profiles}
            customAgents={customAgents}
            onLaunchAgentProfile={handleLaunchProfile}
            onCreateCustomAgent={handleCreateCustomAgent}
            onLaunchCustomAgent={handleLaunchCustomAgent}
            onDeleteCustomAgent={handleDeleteCustomAgent}
            onOpenAgents={() => setMainView('agents')}
            onOpenSkillZone={() => setMainView('skillzone')}
            onSelectDate={(date) => {
              product.actions.selectDate(date);
              setMainView('agenda');
            }}
            onOpenOrganization={() => {
              setMainView('organization');
            }}
            onAddFriend={product.actions.addFriend}
            autoSkillCandidates={product.state.pendingAutoSkills}
            autoSkillLastAction={product.state.lastAutoSkillAction}
            onRefreshAutoSkills={product.actions.refreshPendingAutoSkills}
            onConfirmAutoSkill={product.actions.confirmPendingAutoSkill}
            onRejectAutoSkill={product.actions.rejectPendingAutoSkill}
          />
        </section>
      ) : (
        <div className="otto-content-layout">
          {mainView === 'agenda' ? (
            <DayAgenda
              date={selectedDate}
              schedules={selectedSchedules}
              onCreate={product.actions.createSchedule}
              onDelete={product.actions.deleteSchedule}
              onBack={() => setMainView('chat')}
            />
          ) : mainView === 'skillzone' && edition === 'enterprise' ? (
            <SkillZonePage
              accountId={account.id}
              isAdmin={account.isAdmin}
              onBack={() => setMainView('chat')}
            />
          ) : (
            <ChatView
              session={activeSession}
              messages={activeMessages}
              models={state.models}
              currentModel={state.currentModel}
              userInitial={account.name.slice(0, 1).toUpperCase() || 'O'}
              identityLabel={centralIdentity.identityLabel}
              modelManagementLabel="模型与个人 API 设置"
              busy={busy}
              onSend={handleSend}
              onCancel={actions.cancel}
              onSetModel={actions.setModel}
              onRegenerate={handleRegenerate}
              onRespondQuestion={handleToolConfirmation}
              onOpenSetup={openModelSettings}
              onToggleAgents={() => setMainView('workspace')}
              onNewChat={handleNewChat}
              onClearContext={handleClearContext}
              onExport={
                activeSession
                  ? () => settingsData.actions.exportConversation(activeSession.sessionId)
                  : undefined
              }
              onOpenDoctor={() => openHub('doctor')}
              onOpenFeishu={() => openHub('feishu')}
              onOpenMemory={() => openHub('memory')}
              onOpenSkills={() => openHub('skills')}
              onOpenPrefs={() => openHub('prefs')}
              onOpenSessions={() => setAllConvOpen(true)}
              onShowHelp={handleShowHelp}
              onLaunchAgentProfile={(profileId, title) => {
                setMainView('chat');
                actions.launchAgentProfile(title, profileId);
              }}
              commands={slashCommands}
              onRunServerCommand={(name, args) => {
                if (!activeSession) return;
                transport.send({
                  type: 'run_slash_command',
                  payload: { sessionId: activeSession.sessionId, name, args },
                });
              }}
            />
          )}
          {mainView === 'chat' && uiMode === 'work' ? (
            <RightPanel
              busy={busy}
              mode={edition}
              enterpriseRole={centralIdentity.role}
              enterpriseOrganizationId={account.organizationId}
              workspace={product.state.workspace}
              profiles={centralIdentity.profiles}
              customAgents={customAgents}
              onLaunchAgentProfile={handleLaunchProfile}
              onCreateCustomAgent={handleCreateCustomAgent}
              onLaunchCustomAgent={handleLaunchCustomAgent}
              onDeleteCustomAgent={handleDeleteCustomAgent}
              onOpenAgents={() => setMainView('agents')}
              onOpenSkillZone={() => setMainView('skillzone')}
              onSelectDate={(date) => {
                product.actions.selectDate(date);
                setMainView('agenda');
              }}
              onOpenOrganization={() => setMainView('organization')}
              onAddFriend={product.actions.addFriend}
              autoSkillCandidates={product.state.pendingAutoSkills}
              autoSkillLastAction={product.state.lastAutoSkillAction}
              onRefreshAutoSkills={product.actions.refreshPendingAutoSkills}
              onConfirmAutoSkill={product.actions.confirmPendingAutoSkill}
              onRejectAutoSkill={product.actions.rejectPendingAutoSkill}
            />
          ) : null}
        </div>
      )}

      {state.connection !== 'connected' ? (
        <div className="otto-conn-banner" role="status" aria-live="polite">
          <span className="otto-conn-banner__dot" aria-hidden />
          {state.connection === 'connecting'
            ? '连接中…'
            : '已断开，正在重连…'}
        </div>
      ) : null}

      {allConvOpen ? (
        <AllConversations
          sessions={selectSortedSessions(state)}
          activeSessionId={state.activeSessionId}
          unreadSessions={state.unreadSessions}
          enterpriseUnreadCounts={enterpriseUnreadCounts}
          onSelect={(id) => {
            setMainView('chat');
            actions.selectSession(id);
          }}
          onOpenNotification={openNotificationSession}
          onClose={() => setAllConvOpen(false)}
          onDelete={actions.deleteSession}
        />
      ) : null}

      {state.lastError ? (
        <ErrorToast message={state.lastError} onClose={actions.clearError} />
      ) : null}

      {settingsData.state.exportMessage ? (
        <ErrorToast
          message={settingsData.state.exportMessage}
          onClose={settingsData.actions.clearExportMessage}
        />
      ) : null}

      {product.state.error ? (
        <ErrorToast
          message={product.state.error}
          onClose={product.actions.clearError}
        />
      ) : null}

      {mainView === 'hub' ? (
        <div
          className="otto-hubfloat-overlay"
          onMouseDown={(e) => {
            if (e.target === e.currentTarget) setMainView('chat');
          }}
          onKeyDown={(e) => {
            if (e.key === 'Escape') setMainView('chat');
          }}
        >
          <div className="otto-hubfloat" role="dialog" aria-modal="true" aria-label="设置与诊断中心">
            <SettingsHubPage
              data={settingsData}
              update={softwareUpdate}
              activeSession={activeSession}
              onBack={() => setMainView('chat')}
              initialTab={hubInitialTab}
              product={product}
              models={state.models}
              enterpriseAccount={account}
              uiMode={uiMode}
              onUiModeChange={selectUiMode}
              onManageAccounts={account.isAdmin ? () => setMainView('accounts') : undefined}
            />
          </div>
        </div>
      ) : null}

      {pendingAtoaPermission ? (
        <AtoaPermissionDialog
          request={pendingAtoaPermission}
          onDecision={completeAtoaPermission}
        />
      ) : null}

      {pendingToolConsult ? (
        <AtoaConsultDialog
          account={account}
          member={pendingToolConsult.member}
          schedules={product.state.schedules}
          initialQuestion={pendingToolConsult.question}
          onClose={cancelToolConsult}
          onSent={finishToolConsult}
        />
      ) : null}

      {savedUiMode ? (
        <>
          <WhatsNewDialog />
          <FirstRunGuide mode={uiMode} />
        </>
      ) : null}
      {/* 主动服务提醒：右下角 toast（日程/洞察/日报等） */}
      <ProactiveToast />
      {!savedUiMode ? <UiModeGuide onSelect={selectUiMode} /> : null}
    </div>
  );
}

function ErrorToast({
  message,
  onClose,
}: {
  message: string;
  onClose: () => void;
}): React.JSX.Element {
  useEffect(() => {
    const t = window.setTimeout(onClose, 6000);
    return () => window.clearTimeout(t);
  }, [message, onClose]);

  return (
    <div className="otto-toast" role="alert">
      <span className="otto-toast__msg">{message}</span>
      <button
        type="button"
        className="otto-toast__close"
        onClick={onClose}
        aria-label="关闭提示"
        title="关闭"
      >
        <svg width="13" height="13" viewBox="0 0 24 24" fill="none" aria-hidden>
          <path
            d="M6 6l12 12M18 6L6 18"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
          />
        </svg>
      </button>
    </div>
  );
}
