/**
 * Orchestration 模块统一导出。
 *
 * 包含：
 * - LangGraph 任务编排状态机
 * - OR-Tools 任务分配优化
 * - 多 Agent 协作网络
 * - 主动服务引擎
 * - 离职交接/岗位传承
 */

// LangGraph 任务编排
export {
  buildTaskOrchestrationGraph,
  startTaskOrchestration,
  submitReview,
} from './taskOrchestrator.js';
export type {
  TaskDefinition,
  TaskStatus,
  TaskPriority,
  AllocationSuggestion,
  EmployeeProfile,
  TaskExecutionResult,
  ReviewResult,
} from './taskOrchestrator.js';

// OR-Tools 优化
export { optimizeAllocation, checkOrToolsHealth, dualLayerAllocate } from './ortoolsClient.js';

// 多 Agent 协作
export {
  MultiAgentCollaboration,
  getCollaborationManager,
  initCollaboration,
} from './multiAgent.js';
export type { CollaborationRequest, CollaborationResponse, AgentRegistration, FeishuMessageSender } from './multiAgent.js';

// 主动服务
export { ProactiveService, getProactiveService } from './proactiveService.js';
export type { ProactiveRule, ProactiveContext, ProactiveFeishuSender, ProactiveLocalNotifier, CalendarMeetingResult, CalendarCheckerFn } from './proactiveService.js';

// 离职交接
export { exportMemoryPackage, importMemoryPackage } from './knowledgeTransfer.js';
export type { MemoryPackage } from './knowledgeTransfer.js';

// 工作日志
export {
  WorkLogger,
  getWorkLogger,
  inferCategory,
  describeAction,
  formatLocalDate,
  resolveDefaultWorklogDir,
} from './workLog.js';
export type {
  WorkLogEntry,
  DailySummary,
  WeeklyReport,
  LogCategory,
  WorkLogSearchResult,
  WorkLogSearchOptions,
} from './workLog.js';

// 审计日志
export { AuditLogger, getAuditLogger } from './auditLog.js';
export type { AuditEntry, AuditQueryParams } from './auditLog.js';

// 自动知识沉淀（真实工具/对话生命周期入口）
export {
  KnowledgeCapturePipeline,
  getKnowledgeCapturePipeline,
  formatKnowledgeCaptureStatus,
} from './knowledgeCapturePipeline.js';
export type {
  KnowledgeCaptureStatus,
  CapturedKnowledgeRecord,
  CapturedKnowledgeType,
  KnowledgeSearchOptions,
  KnowledgeSearchResult as CapturedKnowledgeSearchResult,
} from './knowledgeCapturePipeline.js';

// 企业组织架构同步
export { EnterpriseSync, getEnterpriseSync, normalizeRole, getDepartmentFromRole, inferUserRole, createLicenseForUser, checkUserPermission, getRoleLabel } from './enterpriseSync.js';
export type { EnterpriseConfig, UserRole } from './enterpriseSync.js';

// 自动 Skill 生成
export {
  detectPatterns,
  generateSkillCandidates,
  confirmAndSaveSkill,
  confirmPendingSkill,
  rejectSkill,
  rejectPendingSkill,
  listPendingSkillCandidates,
  generateLegacySkillContent,
  resolveAutoSkillUserDir,
  resolveAutoSkillSkillsDir,
  scanAndStageSkillCandidates,
  stageProactiveSkillDraft,
  setAutoSkillFeishuNotifier,
  startAutoSkillScanner,
  stopAutoSkillScanner,
  setRealtimeWatcher,
  getRealtimeWatcher,
} from './autoSkillGenerator.js';
export type {
  SkillCandidate,
  AutoSkillFeishuNotifier,
  AutoSkillScannerOptions,
  PatternDetectionOptions,
  ProactiveSkillDraftInput,
} from './autoSkillGenerator.js';
export {
  installConfirmedSkillDraft,
  stageSkillDraft,
} from './skillDraftWorkflow.js';
export type {
  SkillDraftFileInput,
  SkillDraftRiskSummary,
  SkillDraftStaticTest,
  SkillDraftSummary,
  StageSkillDraftOptions,
} from './skillDraftWorkflow.js';

// 自动 Skill 专家孵化
export {
  generateProfilePipeline,
  loadAutoGeneratedProfiles,
  setAutoSkillConfigForProfile,
} from './autoSkillProfile.js';
export type { AutoSkillProfileData } from './autoSkillProfile.js';

// 自动 Skill 增强（实时触发 / 效果追踪 / 自动优化 / 多项目迁移）
export {
  AutoSkillRealtimeWatcher,
  recordSkillUsage,
  flushSkillUsageWrites,
  getSkillStats,
  getSkillRankings,
  optimizeExistingSkill,
  optimizeAllSkills,
  adaptSkillForProject,
} from './autoSkillEnhance.js';
export type {
  RealtimePatternSummary,
  SkillUsageRecord,
} from './autoSkillEnhance.js';

// 习惯分析引擎（HabitAnalyzer）
export {
  HabitAnalyzer,
  getHabitAnalyzer,
} from './habitAnalyzer.js';
export type { HabitInsight, OperationRecord } from './habitAnalyzer.js';

// Skill 分享
export { SkillShareManager, getSkillShareManager } from './skillShare.js';
export type { SkillShareRecord, ShareSkillParams, ListSharedSkillsParams, ShareStatus, InstallRecord, SkillShareEvent, SkillShareNotification, NotificationSender, SkillComment } from './skillShare.js';
